=== wang-nima/DBHW3_BO/company.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:complexType name="departmenttype">
      <xs:sequence>
         <xs:element name="deptName" type="xs:string"/>
         <xs:element name="deptAddr" type="xs:string"/>
         <xs:element name="deptId">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z]{3}"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>

  
   <xs:complexType name="employeetype">
      <xs:sequence>
         <xs:element name="empId" type="xs:string"/>
         <xs:element name="empName" type="xs:string"/>
         <xs:element name="empPhone">
         	   <xs:simpleType>
			      <xs:restriction base="xs:string">
			         <xs:pattern value="[1-9][0-9]{2}-[0-9]{3}-[0-9]{4}"/>
			      </xs:restriction>
			   </xs:simpleType>
         </xs:element>
         <xs:element name="empOffice" type="xs:string"/>
      </xs:sequence>
   </xs:complexType>


      <xs:complexType name="divisiontype">
         <xs:sequence>
            <xs:element name="divId" type="xs:string"/>
            <xs:element name="divName" type="xs:string"/>
            <xs:element name="managerEmpId" type="xs:integer"/>
            <xs:element name="divPhone">
               <xs:simpleType>
                  <xs:restriction base="xs:string">
                     <xs:pattern value="[1-9][0-9]{2}-[0-9]{3}-[0-9]{4}"/>
                  </xs:restriction>
               </xs:simpleType>
            </xs:element>
            <xs:element name="housedDeptId">
               <xs:simpleType>
                  <xs:restriction base="xs:string">
                     <xs:pattern value="[A-Z][A-Z][A-Z]"/>
                  </xs:restriction>
               </xs:simpleType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>

   <xs:complexType name="worksfortype">
      <xs:sequence>
         <xs:element name="divId" type="xs:string"/>
         <xs:element name="empId" type="xs:string"/>
         <xs:element name="percentTime" type="xs:integer"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="companytype">
      <xs:sequence>
         <xs:element name="Department" maxOccurs="unbounded" type="departmenttype"/>
         <xs:element name="Employee" maxOccurs="unbounded" type="employeetype"/>
         <xs:element name="Division" maxOccurs="unbounded" type="divisiontype"/>
         <xs:element name="WorksFor" maxOccurs="unbounded" type="worksfortype"/>
      </xs:sequence>
   </xs:complexType>
	
	<xs:element name="Company" type="companytype"/>

</xs:schema>

=== wang-nima/DBHW3_BO/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Mon Nov 17 12:28:06 PST 2014 -->
<!-- <?xml-stylesheet type="text/xsl" href="company.xsl"?> -->
<Company xsi:noNamespaceSchemaLocation="company.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Department>
      <deptName>Admin</deptName>
      <deptAddr>LA</deptAddr>
      <deptId>ADM</deptId>
   </Department>
   <Department>
      <deptName>Finance</deptName>
      <deptAddr>LA</deptAddr>
      <deptId>FIN</deptId>
   </Department>
   <Department>
      <deptName>Services</deptName>
      <deptAddr>LA</deptAddr>
      <deptId>SER</deptId>
   </Department>
   <Department>
      <deptName>Operations</deptName>
      <deptAddr>LA</deptAddr>
      <deptId>OPR</deptId>
   </Department>
   <Department>
      <deptName>Business</deptName>
      <deptAddr>LA</deptAddr>
      <deptId>BUS</deptId>
   </Department>
   <Employee>
      <empId>1</empId>
      <empName>PSmith</empName>
      <empPhone>243-235-3253</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>2</empId>
      <empName>Wong</empName>
      <empPhone>224-234-9065</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>3</empId>
      <empName>Jack</empName>
      <empPhone>243-235-4566</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>4</empId>
      <empName>Anne</empName>
      <empPhone>324-876-3768</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>5</empId>
      <empName>Ben</empName>
      <empPhone>453-249-3275</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>6</empId>
      <empName>Monica</empName>
      <empPhone>935-487-3859</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>7</empId>
      <empName>Jennifer</empName>
      <empPhone>935-487-3869</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Employee>
      <empId>8</empId>
      <empName>Mary</empName>
      <empPhone>932-487-3859</empPhone>
      <empOffice>LA</empOffice>
   </Employee>
   <Division>
      <divId>div1</divId>
      <divName>HR</divName>
      <managerEmpId>4</managerEmpId>
      <divPhone>346-232-3242</divPhone>
      <housedDeptId>ADM</housedDeptId>
   </Division>
   <Division>
      <divId>div2</divId>
      <divName>Recruitment</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3243</divPhone>
      <housedDeptId>ADM</housedDeptId>
   </Division>
   <Division>
      <divId>div3</divId>
      <divName>SysAd</divName>
      <managerEmpId>3</managerEmpId>
      <divPhone>346-232-3244</divPhone>
      <housedDeptId>ADM</housedDeptId>
   </Division>
   <Division>
      <divId>div4</divId>
      <divName>Payroll</divName>
      <managerEmpId>5</managerEmpId>
      <divPhone>346-343-3455</divPhone>
      <housedDeptId>FIN</housedDeptId>
   </Division>
   <Division>
      <divId>div5</divId>
      <divName>Accounting</divName>
      <managerEmpId>5</managerEmpId>
      <divPhone>346-232-3246</divPhone>
      <housedDeptId>FIN</housedDeptId>
   </Division>
   <Division>
      <divId>div6</divId>
      <divName>Networking</divName>
      <managerEmpId>2</managerEmpId>
      <divPhone>346-232-3247</divPhone>
      <housedDeptId>SER</housedDeptId>
   </Division>
   <Division>
      <divId>div7</divId>
      <divName>SaaS</divName>
      <managerEmpId>2</managerEmpId>
      <divPhone>346-232-3248</divPhone>
      <housedDeptId>SER</housedDeptId>
   </Division>
   <Division>
      <divId>div8</divId>
      <divName>Security</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3249</divPhone>
      <housedDeptId>SER</housedDeptId>
   </Division>
   <Division>
      <divId>div9</divId>
      <divName>Convergence</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3250</divPhone>
      <housedDeptId>SER</housedDeptId>
   </Division>
   <Division>
      <divId>div10</divId>
      <divName>Sales</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3251</divPhone>
      <housedDeptId>OPR</housedDeptId>
   </Division>
   <Division>
      <divId>div11</divId>
      <divName>Marketing</divName>
      <managerEmpId>4</managerEmpId>
      <divPhone>346-232-3252</divPhone>
      <housedDeptId>OPR</housedDeptId>
   </Division>
   <Division>
      <divId>div12</divId>
      <divName>Engineering</divName>
      <managerEmpId>4</managerEmpId>
      <divPhone>346-232-3253</divPhone>
      <housedDeptId>OPR</housedDeptId>
   </Division>
   <Division>
      <divId>div13</divId>
      <divName>Business Development</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3254</divPhone>
      <housedDeptId>BUS</housedDeptId>
   </Division>
   <Division>
      <divId>div14</divId>
      <divName>Business Analysis</divName>
      <managerEmpId>1</managerEmpId>
      <divPhone>346-232-3255</divPhone>
      <housedDeptId>BUS</housedDeptId>
   </Division>
   <WorksFor>
      <divId>div1</divId>
      <empId>4</empId>
      <percentTime>60</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>4</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>4</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div13</divId>
      <empId>4</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div14</divId>
      <empId>4</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>5</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>5</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div4</divId>
      <empId>5</empId>
      <percentTime>50</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div5</divId>
      <empId>5</empId>
      <percentTime>30</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>3</empId>
      <percentTime>20</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>3</empId>
      <percentTime>20</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div8</divId>
      <empId>3</empId>
      <percentTime>60</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>6</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>6</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div6</divId>
      <empId>6</empId>
      <percentTime>60</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div7</divId>
      <empId>6</empId>
      <percentTime>20</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>1</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>1</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div6</divId>
      <empId>1</empId>
      <percentTime>15</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div8</divId>
      <empId>1</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div10</divId>
      <empId>1</empId>
      <percentTime>60</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div13</divId>
      <empId>1</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div9</divId>
      <empId>1</empId>
      <percentTime>3</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div14</divId>
      <empId>1</empId>
      <percentTime>2</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>2</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>2</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div6</divId>
      <empId>2</empId>
      <percentTime>30</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div7</divId>
      <empId>2</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div1</divId>
      <empId>2</empId>
      <percentTime>10</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div8</divId>
      <empId>2</empId>
      <percentTime>15</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div4</divId>
      <empId>2</empId>
      <percentTime>15</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div7</divId>
      <empId>7</empId>
      <percentTime>90</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>7</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>7</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div11</divId>
      <empId>8</empId>
      <percentTime>90</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div2</divId>
      <empId>8</empId>
      <percentTime>5</percentTime>
   </WorksFor>
   <WorksFor>
      <divId>div3</divId>
      <empId>8</empId>
      <percentTime>5</percentTime>
   </WorksFor>
</Company>
